name: CD

on:
  push:
    branches:
      - main
    paths:
      - "!**/README.md"

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run build
        run: bun run build

      - name: Configure pages
        uses: actions/configure-pages@v3

      - name: Upload build
        uses: actions/upload-pages-artifact@v2
        with:
          path: build

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
