name: CI

on:
  pull_request:
    paths:
      - "!**/README.md"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run checks
        run: |
          yarn check
          yarn build
